import Foundation

// MARK: - Add and media selection

public struct MobileInputSource: Codable, Sendable, Equatable, Identifiable {
    public enum Kind: String, Codable, Sendable, Equatable, CaseIterable {
        case pastedURL
        case clipboardURL
        case sharedURL
        case importedFile
    }

    public var id: String
    public var kind: Kind
    public var value: String
    public var displayName: String?

    public init(
        id: String = UUID().uuidString,
        kind: Kind,
        value: String,
        displayName: String? = nil
    ) {
        self.id = id
        self.kind = kind
        self.value = value
        self.displayName = displayName
    }
}

public enum MobileCandidateKind: String, Codable, Sendable, Equatable, CaseIterable {
    case directFile
    case hlsStream
    case webPageVideo
    case importedFile
}

public enum MobileUnsupportedReason: String, Codable, Sendable, Equatable, CaseIterable {
    case requiresDesktopExtractor
    case drmOrAccessControl
    case loginRequired
    case unsupportedFormat
    case unknown
}

public struct MobileVideoCandidate: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var sourceURL: String
    public var kind: MobileCandidateKind
    public var title: String
    public var detail: String?
    public var unsupportedReason: MobileUnsupportedReason?

    public var isSupportedOnMobile: Bool {
        unsupportedReason == nil
    }

    public init(
        id: String,
        sourceURL: String,
        kind: MobileCandidateKind,
        title: String,
        detail: String? = nil,
        unsupportedReason: MobileUnsupportedReason? = nil
    ) {
        self.id = id
        self.sourceURL = sourceURL
        self.kind = kind
        self.title = title
        self.detail = detail
        self.unsupportedReason = unsupportedReason
    }
}

public struct MobileFormatChoice: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var label: String
    public var detail: String?
    public var height: Int?
    public var isAudioOnly: Bool

    public init(
        id: String,
        label: String,
        detail: String? = nil,
        height: Int? = nil,
        isAudioOnly: Bool = false
    ) {
        self.id = id
        self.label = label
        self.detail = detail
        self.height = height
        self.isAudioOnly = isAudioOnly
    }
}

public struct MobileSubtitleChoice: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var languageCode: String
    public var label: String
    public var isAutoGenerated: Bool
    public var source: MobileSubtitleSource?

    public init(
        id: String,
        languageCode: String,
        label: String,
        isAutoGenerated: Bool,
        source: MobileSubtitleSource? = nil
    ) {
        self.id = id
        self.languageCode = languageCode
        self.label = label
        self.isAutoGenerated = isAutoGenerated
        self.source = source
    }
}

public enum MobileSubtitleSource: Codable, Sendable, Equatable {
    case localFile(URL)
    case remoteURL(String)
}

public struct MobileVideoInfo: Codable, Sendable, Equatable {
    public var candidate: MobileVideoCandidate
    public var videoID: String
    public var title: String
    public var durationSeconds: Double?
    public var thumbnailURL: String?
    public var formats: [MobileFormatChoice]
    public var subtitles: [MobileSubtitleChoice]

    public var recommendedFormat: MobileFormatChoice? {
        formats.first { !$0.isAudioOnly } ?? formats.first
    }

    public var hasSubtitleOptions: Bool {
        !subtitles.isEmpty
    }

    public init(
        candidate: MobileVideoCandidate,
        videoID: String,
        title: String,
        durationSeconds: Double? = nil,
        thumbnailURL: String? = nil,
        formats: [MobileFormatChoice] = [],
        subtitles: [MobileSubtitleChoice] = []
    ) {
        self.candidate = candidate
        self.videoID = videoID
        self.title = title
        self.durationSeconds = durationSeconds
        self.thumbnailURL = thumbnailURL
        self.formats = formats
        self.subtitles = subtitles
    }
}

public enum MobileAddSessionState: String, Codable, Sendable, Equatable, CaseIterable {
    case idle
    case analyzing
    case candidateSelection
    case ready
    case unsupported
    case failed
}

public struct MobileAddSessionSnapshot: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var input: MobileInputSource?
    public var state: MobileAddSessionState
    public var candidates: [MobileVideoCandidate]
    public var selectedCandidateID: String?
    public var videoInfo: MobileVideoInfo?
    public var error: MobileTaskError?

    public var selectedCandidate: MobileVideoCandidate? {
        guard let selectedCandidateID else { return nil }
        return candidates.first { $0.id == selectedCandidateID }
    }

    public init(
        id: String,
        input: MobileInputSource? = nil,
        state: MobileAddSessionState = .idle,
        candidates: [MobileVideoCandidate] = [],
        selectedCandidateID: String? = nil,
        videoInfo: MobileVideoInfo? = nil,
        error: MobileTaskError? = nil
    ) {
        self.id = id
        self.input = input
        self.state = state
        self.candidates = candidates
        self.selectedCandidateID = selectedCandidateID
        self.videoInfo = videoInfo
        self.error = error
    }
}

public struct MobileDownloadRequest: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var sourceURL: String
    public var candidateID: String
    public var videoID: String
    public var formatID: String
    public var subtitleIDs: [String]
    public var autoSubtitleIDs: [String]
    public var exportProfile: MobileExportProfile
    public var preferredTitle: String?

    public init(
        id: String,
        sourceURL: String,
        candidateID: String,
        videoID: String,
        formatID: String,
        subtitleIDs: [String] = [],
        autoSubtitleIDs: [String] = [],
        exportProfile: MobileExportProfile = MobileExportProfile(),
        preferredTitle: String? = nil
    ) {
        self.id = id
        self.sourceURL = sourceURL
        self.candidateID = candidateID
        self.videoID = videoID
        self.formatID = formatID
        self.subtitleIDs = subtitleIDs
        self.autoSubtitleIDs = autoSubtitleIDs
        self.exportProfile = exportProfile
        self.preferredTitle = preferredTitle
    }
}

public struct MobileDownloadSelection: Codable, Sendable, Equatable {
    public var candidateID: String
    public var formatID: String
    public var subtitleIDs: [String]
    public var autoSubtitleIDs: [String]

    public init(
        candidateID: String,
        formatID: String,
        subtitleIDs: [String] = [],
        autoSubtitleIDs: [String] = []
    ) {
        self.candidateID = candidateID
        self.formatID = formatID
        self.subtitleIDs = subtitleIDs
        self.autoSubtitleIDs = autoSubtitleIDs
    }
}

/// Mobile-safe queue states. These describe user-visible work, not desktop process state.
public enum MobileTaskState: String, Codable, Sendable, Equatable, CaseIterable {
    case waiting
    case analyzing
    case ready
    case downloading
    case translating
    case exporting
    case needsForegroundToContinue
    case completed
    case failed
    case cancelled
}

/// Error buckets mobile UI can use to decide whether to show a user action or a system limitation.
public enum MobileTaskError: String, Codable, Sendable, Error, Equatable, CaseIterable {
    case unsupportedOnMobile
    case sourceUnavailableAfterRelaunch
    case networkUnavailable
    case credentialRequired
    case permissionDenied
    case storageFull
    case systemBackgroundLimit
    case exportFailed
    case cancelled
    case unknown

    public var isUserFixable: Bool {
        switch self {
        case .credentialRequired, .permissionDenied, .storageFull, .networkUnavailable:
            return true
        case .unsupportedOnMobile, .sourceUnavailableAfterRelaunch, .systemBackgroundLimit, .exportFailed, .cancelled, .unknown:
            return false
        }
    }
}

/// Mobile export intent. Platform renderers decide whether this maps to a subtitle file, soft subtitle, or render pass.
public struct MobileExportProfile: Codable, Sendable, Equatable {
    public enum SubtitleMode: String, Codable, Sendable, Equatable, CaseIterable {
        case none
        case translatedSubtitleFile
        case softSubtitle
        case burnedInSubtitle
    }

    public var subtitleMode: SubtitleMode
    public var maxRenderHeight: Int?

    public var requiresVideoRender: Bool {
        subtitleMode == .burnedInSubtitle
    }

    public init(
        subtitleMode: SubtitleMode = .translatedSubtitleFile,
        maxRenderHeight: Int? = 1080
    ) {
        self.subtitleMode = subtitleMode
        self.maxRenderHeight = maxRenderHeight
    }
}

/// Shared mobile platforms for domain state passed between iOS and Android layers.
public enum MobilePlatform: String, Codable, Sendable, Equatable, CaseIterable {
    case iOS = "ios"
    case android
}

/// A coarse task phase used for progress reporting. Terminal success or failure remains in `MobileTaskState`.
public enum MobileTaskPhase: String, Codable, Sendable, Equatable, CaseIterable {
    case waiting
    case analyzing
    case downloading
    case translating
    case exporting
}

/// Platform-neutral progress. Unit counts may be bytes, files, segments, or logical steps.
public struct MobileTaskProgress: Codable, Sendable, Equatable {
    public var phase: MobileTaskPhase
    public var completedUnitCount: Int
    public var totalUnitCount: Int?

    public var fractionCompleted: Double? {
        guard let totalUnitCount, totalUnitCount > 0 else {
            return nil
        }

        let fraction = Double(completedUnitCount) / Double(totalUnitCount)
        return min(max(fraction, 0), 1)
    }

    public init(
        phase: MobileTaskPhase = .waiting,
        completedUnitCount: Int = 0,
        totalUnitCount: Int? = nil
    ) {
        self.phase = phase
        self.completedUnitCount = completedUnitCount
        self.totalUnitCount = totalUnitCount
    }
}

/// File or media outputs that a mobile task can produce.
public enum MobileArtifactKind: String, Codable, Sendable, Equatable, CaseIterable {
    case originalMedia
    case translatedSubtitleFile
    case softSubtitle
    case renderedVideo
    case transcript
    case metadata
}

/// A produced mobile artifact. `storageIdentifier` is an app-owned reference, not a credential.
public struct MobileTaskArtifact: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var kind: MobileArtifactKind
    public var displayName: String
    public var storageIdentifier: String
    public var byteCount: Int?

    public init(
        id: String,
        kind: MobileArtifactKind,
        displayName: String,
        storageIdentifier: String,
        byteCount: Int? = nil
    ) {
        self.id = id
        self.kind = kind
        self.displayName = displayName
        self.storageIdentifier = storageIdentifier
        self.byteCount = byteCount
    }
}

/// Completed task outputs.
public struct MobileTaskResult: Codable, Sendable, Equatable {
    public var artifacts: [MobileTaskArtifact]
    public var primaryArtifactID: String?

    public var primaryArtifact: MobileTaskArtifact? {
        guard let primaryArtifactID else {
            return nil
        }

        return artifacts.first { $0.id == primaryArtifactID }
    }

    public init(
        artifacts: [MobileTaskArtifact] = [],
        primaryArtifactID: String? = nil
    ) {
        self.artifacts = artifacts
        self.primaryArtifactID = primaryArtifactID
    }
}

public enum MobileTaskAction: String, Codable, Sendable, Equatable, CaseIterable {
    case startDownload
    case exportTranslatedSubtitle
    case exportRenderedVideo
    case pause
    case resume
    case cancel
    case retry
    case openAppToContinue
    case openResult
    case shareResult
    case remove
}

/// Coarse capabilities available to a mobile worker on a given platform.
public enum MobileProcessingCapability: String, Codable, Sendable, Equatable, CaseIterable {
    case analysis
    case download
    case translation
    case subtitleExport
    case videoRender
    case backgroundTransfer
    case backgroundRender
    case localTranslationModel
    case cloudTranslation
    case appleIntelligence
}

public struct MobileProcessingCapabilities: Codable, Sendable, Equatable {
    public var platform: MobilePlatform
    public var supportedCapabilities: [MobileProcessingCapability]
    public var maxRenderHeight: Int?

    public func supports(_ capability: MobileProcessingCapability) -> Bool {
        supportedCapabilities.contains(capability)
    }

    public func canSatisfy(_ profile: MobileExportProfile) -> Bool {
        switch profile.subtitleMode {
        case .none:
            return supports(.download)
        case .translatedSubtitleFile:
            return supports(.translation) && supports(.subtitleExport)
        case .softSubtitle:
            return supports(.subtitleExport)
        case .burnedInSubtitle:
            guard supports(.videoRender) else { return false }
            guard let requestedHeight = profile.maxRenderHeight,
                  let maxRenderHeight else {
                return true
            }
            return requestedHeight <= maxRenderHeight
        }
    }

    public init(
        platform: MobilePlatform,
        supportedCapabilities: [MobileProcessingCapability] = [],
        maxRenderHeight: Int? = nil
    ) {
        self.platform = platform
        self.supportedCapabilities = supportedCapabilities
        self.maxRenderHeight = maxRenderHeight
    }
}

/// Mobile background execution is always system bounded. This type only records the current policy state.
public enum MobileBackgroundExecution: String, Codable, Sendable, Equatable, CaseIterable {
    case foregroundRequired
    case backgroundTransfer
    case continuedProcessing
    case scheduledWork
    case systemManaged
    case systemDeferred
    case systemInterrupted
}

public enum MobileBackgroundResumability: String, Codable, Sendable, Equatable, CaseIterable {
    case resumable
    case nonResumable
}

public enum MobileBackgroundLimit: String, Codable, Sendable, Equatable, CaseIterable {
    case foregroundRequired
    case systemTimeLimit
    case systemDeferred
    case systemInterrupted
    case notResumable
    case requiresExternalPower
    case requiresUnmeteredNetwork
    case userVisibleNotificationRequired
}

public struct MobileBackgroundPolicy: Codable, Sendable, Equatable {
    public var execution: MobileBackgroundExecution
    public var resumability: MobileBackgroundResumability
    public var systemTimeLimitSeconds: Int?
    public var limits: [MobileBackgroundLimit]

    public var requiresForeground: Bool {
        execution == .foregroundRequired || limits.contains(.foregroundRequired)
    }

    public var isSystemLimited: Bool {
        switch execution {
        case .foregroundRequired:
            return limits.contains { limit in
                limit == .systemTimeLimit || limit == .systemDeferred || limit == .systemInterrupted
            }
        case .backgroundTransfer, .continuedProcessing, .scheduledWork, .systemManaged, .systemDeferred, .systemInterrupted:
            return true
        }
    }

    public var canResume: Bool {
        resumability == .resumable && !limits.contains(.notResumable)
    }

    public var allowsUnboundedBackgroundExecution: Bool {
        false
    }

    public init(
        execution: MobileBackgroundExecution = .foregroundRequired,
        resumability: MobileBackgroundResumability = .resumable,
        systemTimeLimitSeconds: Int? = nil,
        limits: [MobileBackgroundLimit] = []
    ) {
        self.execution = execution
        self.resumability = resumability
        self.systemTimeLimitSeconds = systemTimeLimitSeconds
        self.limits = limits
    }
}

public enum MobileDesignSystem: String, Codable, Sendable, Equatable, CaseIterable {
    case appleHIG
    case material3
}

public enum MobileSurface: String, Codable, Sendable, Equatable, CaseIterable {
    case add
    case queue
    case library
    case settings
}

public struct MobilePlatformProfile: Codable, Sendable, Equatable {
    public var platform: MobilePlatform
    public var designSystem: MobileDesignSystem
    public var surfaces: [MobileSurface]
    public var capabilities: MobileProcessingCapabilities
    public var defaultBackgroundPolicy: MobileBackgroundPolicy

    public static let iOSDefault = MobilePlatformProfile(
        platform: .iOS,
        designSystem: .appleHIG,
        surfaces: [.add, .queue, .library, .settings],
        capabilities: MobileProcessingCapabilities(platform: .iOS),
        defaultBackgroundPolicy: MobileBackgroundPolicy()
    )

    public static let androidDefault = MobilePlatformProfile(
        platform: .android,
        designSystem: .material3,
        surfaces: [.add, .queue, .library, .settings],
        capabilities: MobileProcessingCapabilities(platform: .android),
        defaultBackgroundPolicy: MobileBackgroundPolicy()
    )

    public init(
        platform: MobilePlatform,
        designSystem: MobileDesignSystem,
        surfaces: [MobileSurface],
        capabilities: MobileProcessingCapabilities,
        defaultBackgroundPolicy: MobileBackgroundPolicy
    ) {
        self.platform = platform
        self.designSystem = designSystem
        self.surfaces = surfaces
        self.capabilities = capabilities
        self.defaultBackgroundPolicy = defaultBackgroundPolicy
    }
}

/// A portable task snapshot that can be persisted or mirrored across mobile UI and workers.
public struct MobileTaskSnapshot: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var platform: MobilePlatform
    public var state: MobileTaskState
    public var progress: MobileTaskProgress
    public var downloadSelection: MobileDownloadSelection?
    public var exportProfile: MobileExportProfile
    public var capabilities: MobileProcessingCapabilities
    public var backgroundPolicy: MobileBackgroundPolicy
    public var executionGenerationID: String?
    public var result: MobileTaskResult?
    public var error: MobileTaskError?

    public var availableActions: [MobileTaskAction] {
        switch state {
        case .waiting, .ready:
            return [.startDownload, .cancel]
        case .analyzing:
            return [.cancel]
        case .downloading, .translating, .exporting:
            return backgroundPolicy.canResume ? [.pause, .cancel] : [.cancel]
        case .needsForegroundToContinue:
            return [.openAppToContinue, .cancel]
        case .completed:
            guard let result, !result.artifacts.isEmpty else {
                return [.remove]
            }
            var actions: [MobileTaskAction] = []
            if (exportProfile.subtitleMode == .translatedSubtitleFile ||
                exportProfile.subtitleMode == .softSubtitle),
               result.artifacts.contains(where: { $0.kind == .transcript }),
               !result.artifacts.contains(where: { artifact in
                   switch exportProfile.subtitleMode {
                   case .translatedSubtitleFile:
                       return artifact.kind == .translatedSubtitleFile
                   case .softSubtitle:
                       return artifact.kind == .softSubtitle
                   case .none, .burnedInSubtitle:
                       return false
                   }
               }) {
                actions.append(.exportTranslatedSubtitle)
            }
            if exportProfile.requiresVideoRender,
               capabilities.canSatisfy(exportProfile),
               result.artifacts.contains(where: { $0.kind == .originalMedia }),
               result.artifacts.contains(where: { $0.kind == .translatedSubtitleFile }),
               !result.artifacts.contains(where: { $0.kind == .renderedVideo }) {
                actions.append(.exportRenderedVideo)
            }
            actions.append(contentsOf: [.openResult, .shareResult, .remove])
            return actions
        case .failed:
            return [.retry, .remove]
        case .cancelled:
            return [.remove]
        }
    }

    public init(
        id: String,
        platform: MobilePlatform,
        state: MobileTaskState = .waiting,
        progress: MobileTaskProgress = MobileTaskProgress(),
        downloadSelection: MobileDownloadSelection? = nil,
        exportProfile: MobileExportProfile = MobileExportProfile(),
        capabilities: MobileProcessingCapabilities? = nil,
        backgroundPolicy: MobileBackgroundPolicy = MobileBackgroundPolicy(),
        executionGenerationID: String? = nil,
        result: MobileTaskResult? = nil,
        error: MobileTaskError? = nil
    ) {
        self.id = id
        self.platform = platform
        self.state = state
        self.progress = progress
        self.downloadSelection = downloadSelection
        self.exportProfile = exportProfile
        self.capabilities = capabilities ?? MobileProcessingCapabilities(platform: platform)
        self.backgroundPolicy = backgroundPolicy
        self.executionGenerationID = executionGenerationID
        self.result = result
        self.error = error
    }
}

// MARK: - Library

public enum MobileLibraryState: String, Codable, Sendable, Equatable, CaseIterable {
    case available
    case fileMissing
    case permissionDenied
    case deleting
}

public enum MobileLibraryAction: String, Codable, Sendable, Equatable, CaseIterable {
    case open
    case share
    case saveToFiles
    case saveToPhotos
    case deleteRecord
    case locateFile
}

public enum MobileLibraryActionPresentation: String, Codable, Sendable, Equatable, CaseIterable {
    case inAppOpen
    case shareSheet
    case fileExporter
    case photoLibraryExporter
    case documentPicker
    case confirmationOnly
    case unavailable
}

public enum MobileLibraryActionOutcomeStatus: String, Codable, Sendable, Equatable, CaseIterable {
    case prepared
    case requiresSystemPresentation
    case completed
    case unavailable
    case failed
}

public struct MobileLibraryActionOutcome: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var action: MobileLibraryAction
    public var itemID: String
    public var itemTitle: String
    public var artifacts: [MobileTaskArtifact]
    public var presentation: MobileLibraryActionPresentation
    public var status: MobileLibraryActionOutcomeStatus
    public var statusMessage: String
    public var requiresSystemUI: Bool
    public var completedRecordMutation: Bool

    public init(
        id: String = UUID().uuidString,
        action: MobileLibraryAction,
        itemID: String,
        itemTitle: String,
        artifacts: [MobileTaskArtifact] = [],
        presentation: MobileLibraryActionPresentation,
        status: MobileLibraryActionOutcomeStatus,
        statusMessage: String,
        requiresSystemUI: Bool,
        completedRecordMutation: Bool = false
    ) {
        self.id = id
        self.action = action
        self.itemID = itemID
        self.itemTitle = itemTitle
        self.artifacts = artifacts
        self.presentation = presentation
        self.status = status
        self.statusMessage = statusMessage
        self.requiresSystemUI = requiresSystemUI
        self.completedRecordMutation = completedRecordMutation
    }
}

public struct MobileLibraryItem: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var title: String
    public var createdAt: Date
    public var artifacts: [MobileTaskArtifact]
    public var state: MobileLibraryState
    public var sourceTaskID: String?

    public var availableActions: [MobileLibraryAction] {
        switch state {
        case .available:
            let hasVideo = artifacts.contains { $0.kind == .renderedVideo || $0.kind == .originalMedia }
            return hasVideo ? [.open, .share, .saveToFiles, .saveToPhotos, .deleteRecord] : [.open, .share, .saveToFiles, .deleteRecord]
        case .fileMissing:
            return [.locateFile, .deleteRecord]
        case .permissionDenied:
            return [.saveToFiles, .deleteRecord]
        case .deleting:
            return []
        }
    }

    public init(
        id: String,
        title: String,
        createdAt: Date,
        artifacts: [MobileTaskArtifact],
        state: MobileLibraryState = .available,
        sourceTaskID: String? = nil
    ) {
        self.id = id
        self.title = title
        self.createdAt = createdAt
        self.artifacts = artifacts
        self.state = state
        self.sourceTaskID = sourceTaskID
    }
}

// MARK: - Translation, processing, export, and repositories

public struct SecureCredentialReference: Codable, Sendable, Equatable, Hashable {
    public var service: String
    public var account: String
    public var displayName: String?

    public init(service: String, account: String, displayName: String? = nil) {
        self.service = service
        self.account = account
        self.displayName = displayName
    }
}

public enum MobileTranslationCredentialRequirement: String, Codable, Sendable, Equatable, CaseIterable {
    case none
    case secureCredential
    case localModel
    case runtimeEntitlement
}

public struct MobileTranslationConfiguration: Codable, Sendable, Equatable {
    public var engine: TranslationEngine
    public var baseURL: String?
    public var model: String?
    public var credential: SecureCredentialReference?
    public var readiness: TranslationReadiness

    public var credentialRequirement: MobileTranslationCredentialRequirement {
        switch engine {
        case .anthropicCompatible, .openAICompatible:
            return .secureCredential
        case .appleTranslationLowLatency, .appleTranslationHighFidelity:
            return .runtimeEntitlement
        case .appleFoundationOnDevice:
            return .localModel
        case .appleFoundationPCC, .appleFoundationCloudPro:
            return .runtimeEntitlement
        }
    }

    public var usesCloudService: Bool {
        switch engine {
        case .anthropicCompatible, .openAICompatible, .appleFoundationPCC, .appleFoundationCloudPro:
            return true
        case .appleTranslationLowLatency, .appleTranslationHighFidelity, .appleFoundationOnDevice:
            return false
        }
    }

    public var isRunnableWithoutUserCredential: Bool {
        credentialRequirement != .secureCredential
    }

    public static func conservativeReadiness(for engine: TranslationEngine) -> TranslationReadiness {
        switch engine {
        case .anthropicCompatible, .openAICompatible:
            return TranslationReadiness(issues: [
                TranslationReadinessIssue(kind: .needsConfiguration)
            ])
        case .appleTranslationLowLatency, .appleTranslationHighFidelity:
            return TranslationReadiness(issues: [
                TranslationReadinessIssue(kind: .needsRuntimeVerification),
                TranslationReadinessIssue(kind: .needsLanguageDownload)
            ])
        case .appleFoundationOnDevice:
            return TranslationReadiness(issues: [
                TranslationReadinessIssue(kind: .appleIntelligenceUnavailable),
                TranslationReadinessIssue(kind: .modelUnavailable)
            ])
        case .appleFoundationPCC:
            return TranslationReadiness(issues: [
                TranslationReadinessIssue(kind: .pccUnavailable)
            ])
        case .appleFoundationCloudPro:
            return TranslationReadiness(issues: [
                TranslationReadinessIssue(
                    kind: .pccUnavailable,
                    message: "Apple Intelligence Cloud Pro（云端 Pro）当前不可用。"
                )
            ])
        }
    }

    public init(
        engine: TranslationEngine,
        baseURL: String? = nil,
        model: String? = nil,
        credential: SecureCredentialReference? = nil,
        readiness: TranslationReadiness? = nil
    ) {
        self.engine = engine
        self.baseURL = baseURL
        self.model = model
        self.credential = credential
        self.readiness = readiness ?? Self.conservativeReadiness(for: engine)
    }
}

public struct MobileTranslationSegment: Codable, Sendable, Equatable, Identifiable {
    public var id: String
    public var startTime: String
    public var endTime: String
    public var text: String

    public init(id: String, startTime: String, endTime: String, text: String) {
        self.id = id
        self.startTime = startTime
        self.endTime = endTime
        self.text = text
    }
}

public struct MobileTranslationRequest: Codable, Sendable, Equatable {
    public var segments: [MobileTranslationSegment]
    public var context: TranslationContext

    public init(segments: [MobileTranslationSegment], context: TranslationContext) {
        self.segments = segments
        self.context = context
    }
}

public struct MobileTranslationResult: Codable, Sendable, Equatable {
    public var segments: [MobileTranslationSegment]

    public init(segments: [MobileTranslationSegment]) {
        self.segments = segments
    }
}

public struct MobileSubtitleProcessingRequest: Codable, Sendable, Equatable {
    public var sourceSubtitle: MobileTaskArtifact
    public var translation: MobileTranslationResult
    public var exportProfile: MobileExportProfile

    public init(
        sourceSubtitle: MobileTaskArtifact,
        translation: MobileTranslationResult,
        exportProfile: MobileExportProfile
    ) {
        self.sourceSubtitle = sourceSubtitle
        self.translation = translation
        self.exportProfile = exportProfile
    }
}

public struct MobileRenderRequest: Codable, Sendable, Equatable {
    public var sourceMedia: MobileTaskArtifact
    public var subtitles: [MobileTaskArtifact]
    public var exportProfile: MobileExportProfile

    public init(
        sourceMedia: MobileTaskArtifact,
        subtitles: [MobileTaskArtifact] = [],
        exportProfile: MobileExportProfile
    ) {
        self.sourceMedia = sourceMedia
        self.subtitles = subtitles
        self.exportProfile = exportProfile
    }
}

public protocol MobileParser: Sendable {
    func resolveCandidates(for input: MobileInputSource) async throws -> [MobileVideoCandidate]
    func analyze(candidate: MobileVideoCandidate) async throws -> MobileVideoInfo
}

public protocol MobileDownloadEngine: Sendable {
    func download(
        _ request: MobileDownloadRequest,
        progress: @escaping @Sendable (MobileTaskProgress) -> Void
    ) async throws -> MobileTaskResult
}

public protocol MobileTranslationProvider: Sendable {
    func readiness(for context: TranslationContext) async -> TranslationReadiness
    func translate(_ request: MobileTranslationRequest) async throws -> MobileTranslationResult
}

public enum MobileTranslationProviderError: Error, Sendable, Equatable {
    case unsupportedEngine
    case invalidConfiguration
    case missingCredential
    case invalidResponse
    case requestFailed(Int)
}

public struct MobileTranslationTransportRequest: Sendable, Equatable {
    public var url: URL
    public var method: String
    public var headers: [String: String]
    public var body: Data

    public init(
        url: URL,
        method: String = "POST",
        headers: [String: String],
        body: Data
    ) {
        self.url = url
        self.method = method
        self.headers = headers
        self.body = body
    }
}

public struct MobileTranslationTransportResponse: Sendable, Equatable {
    public var statusCode: Int
    public var body: Data

    public init(statusCode: Int, body: Data) {
        self.statusCode = statusCode
        self.body = body
    }
}

public protocol MobileTranslationTransport: Sendable {
    func send(_ request: MobileTranslationTransportRequest) async throws -> MobileTranslationTransportResponse
}

public struct APICompatibleMobileTranslationProvider: MobileTranslationProvider {
    public var configuration: MobileTranslationConfiguration

    private let credentialStore: any SecureCredentialStore
    private let transport: any MobileTranslationTransport

    public init(
        configuration: MobileTranslationConfiguration,
        credentialStore: any SecureCredentialStore,
        transport: any MobileTranslationTransport
    ) {
        self.configuration = configuration
        self.credentialStore = credentialStore
        self.transport = transport
    }

    public func readiness(for context: TranslationContext) async -> TranslationReadiness {
        do {
            _ = try await validatedConfiguration()
            _ = try endpointURL(
                baseURL: configuration.baseURL ?? "",
                endpointPath: configuration.engine == .openAICompatible ? "/v1/chat/completions" : "/v1/messages"
            )
            return .ready
        } catch {
            return TranslationReadiness(issues: [TranslationReadinessIssue(kind: .needsConfiguration)])
        }
    }

    public func translate(_ request: MobileTranslationRequest) async throws -> MobileTranslationResult {
        let valid = try await validatedConfiguration()
        let transportRequest: MobileTranslationTransportRequest
        switch configuration.engine {
        case .openAICompatible:
            transportRequest = try makeOpenAIRequest(valid: valid, translationRequest: request)
        case .anthropicCompatible:
            transportRequest = try makeAnthropicRequest(valid: valid, translationRequest: request)
        case .appleTranslationLowLatency,
             .appleTranslationHighFidelity,
             .appleFoundationOnDevice,
             .appleFoundationPCC,
             .appleFoundationCloudPro:
            throw MobileTranslationProviderError.unsupportedEngine
        }

        let response = try await transport.send(transportRequest)
        guard response.statusCode == 200 else {
            throw MobileTranslationProviderError.requestFailed(response.statusCode)
        }
        return try parseTranslationResponse(response.body, original: request)
    }

    private struct ValidConfiguration {
        var baseURL: String
        var model: String
        var secret: String
    }

    private func validatedConfiguration() async throws -> ValidConfiguration {
        guard configuration.engine == .openAICompatible || configuration.engine == .anthropicCompatible else {
            throw MobileTranslationProviderError.unsupportedEngine
        }
        guard let baseURL = configuration.baseURL?.trimmingCharacters(in: .whitespacesAndNewlines),
              !baseURL.isEmpty,
              let model = configuration.model?.trimmingCharacters(in: .whitespacesAndNewlines),
              !model.isEmpty,
              let credential = configuration.credential else {
            throw MobileTranslationProviderError.invalidConfiguration
        }
        guard let secret = try await credentialStore.credential(for: credential)?
            .trimmingCharacters(in: .whitespacesAndNewlines),
            !secret.isEmpty else {
            throw MobileTranslationProviderError.missingCredential
        }
        return ValidConfiguration(baseURL: baseURL, model: model, secret: normalizedBearerSecret(secret))
    }

    private func makeOpenAIRequest(
        valid: ValidConfiguration,
        translationRequest: MobileTranslationRequest
    ) throws -> MobileTranslationTransportRequest {
        // 用最通用的 Chat Completions 端点：官方/Azure 及绝大多数"OpenAI 兼容"网关都支持，
        // 而 /v1/responses 是 OpenAI 私有新端点，多数兼容服务不实现，会导致请求失败。
        let url = try endpointURL(baseURL: valid.baseURL, endpointPath: "/v1/chat/completions")
        struct Message: Encodable {
            let role: String
            let content: String
        }
        struct Payload: Encodable {
            let model: String
            let messages: [Message]
            let max_completion_tokens: Int
        }
        let instructions = "Translate each numbered subtitle segment to \(translationRequest.context.targetLanguage). Preserve numbering as '<id>=<translation>'."
        let payload = Payload(
            model: valid.model,
            messages: [
                Message(role: "system", content: instructions),
                Message(role: "user", content: numberedInput(from: translationRequest.segments))
            ],
            max_completion_tokens: max(1024, translationRequest.segments.count * 128)
        )
        return MobileTranslationTransportRequest(
            url: url,
            headers: [
                "content-type": "application/json",
                "Authorization": "Bearer \(valid.secret)"
            ],
            body: try JSONEncoder().encode(payload)
        )
    }

    private func makeAnthropicRequest(
        valid: ValidConfiguration,
        translationRequest: MobileTranslationRequest
    ) throws -> MobileTranslationTransportRequest {
        let url = try endpointURL(baseURL: valid.baseURL, endpointPath: "/v1/messages")
        struct Message: Encodable {
            let role: String
            let content: String
        }
        struct Payload: Encodable {
            let model: String
            let max_tokens: Int
            let system: String
            let messages: [Message]
        }
        let payload = Payload(
            model: valid.model,
            max_tokens: max(1024, translationRequest.segments.count * 128),
            system: "Translate each numbered subtitle segment to \(translationRequest.context.targetLanguage). Preserve numbering as '<id>=<translation>'.",
            messages: [Message(role: "user", content: numberedInput(from: translationRequest.segments))]
        )
        return MobileTranslationTransportRequest(
            url: url,
            headers: anthropicHeaders(url: url, secret: valid.secret),
            body: try JSONEncoder().encode(payload)
        )
    }

    private func anthropicHeaders(url: URL, secret: String) -> [String: String] {
        var headers = [
            "content-type": "application/json",
            "anthropic-version": "2023-06-01",
            "x-api-key": secret
        ]
        if url.host?.lowercased() != "api.anthropic.com" {
            headers["Authorization"] = "Bearer \(secret)"
        }
        return headers
    }

    private func parseTranslationResponse(
        _ body: Data,
        original: MobileTranslationRequest
    ) throws -> MobileTranslationResult {
        let text: String
        do {
            text = try responseText(from: body, engine: configuration.engine)
        } catch let error as MobileTranslationProviderError {
            throw error
        } catch {
            throw MobileTranslationProviderError.invalidResponse
        }
        let translations = parseNumberedTranslations(text)
        guard !translations.isEmpty else {
            throw MobileTranslationProviderError.invalidResponse
        }
        return MobileTranslationResult(
            segments: original.segments.map { segment in
                MobileTranslationSegment(
                    id: segment.id,
                    startTime: segment.startTime,
                    endTime: segment.endTime,
                    text: translations[segment.id] ?? segment.text
                )
            }
        )
    }

    private func responseText(from body: Data, engine: TranslationEngine) throws -> String {
        switch engine {
        case .openAICompatible:
            struct Choice: Decodable {
                struct Msg: Decodable { let content: String? }
                let message: Msg?
            }
            struct Reply: Decodable {
                let choices: [Choice]
            }
            let reply = try JSONDecoder().decode(Reply.self, from: body)
            let text = (reply.choices.first?.message?.content ?? "")
            guard !text.isEmpty else {
                throw MobileTranslationProviderError.invalidResponse
            }
            return text
        case .anthropicCompatible:
            struct Block: Decodable {
                let type: String
                let text: String?
            }
            struct Reply: Decodable {
                let content: [Block]
            }
            let reply = try JSONDecoder().decode(Reply.self, from: body)
            var parts: [String] = []
            for block in reply.content where block.type == "text" {
                if let text = block.text {
                    parts.append(text)
                }
            }
            let text = parts.joined()
            guard !text.isEmpty else {
                throw MobileTranslationProviderError.invalidResponse
            }
            return text
        case .appleTranslationLowLatency,
             .appleTranslationHighFidelity,
             .appleFoundationOnDevice,
             .appleFoundationPCC,
             .appleFoundationCloudPro:
            throw MobileTranslationProviderError.unsupportedEngine
        }
    }

    private func parseNumberedTranslations(_ text: String) -> [String: String] {
        var result: [String: String] = [:]
        for line in text.components(separatedBy: .newlines) {
            let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
            guard let separator = trimmed.firstIndex(of: "=") else {
                continue
            }
            let key = trimmed[..<separator].trimmingCharacters(in: .whitespacesAndNewlines)
            let value = trimmed[trimmed.index(after: separator)...].trimmingCharacters(in: .whitespacesAndNewlines)
            if !key.isEmpty, !value.isEmpty {
                result[key] = value
            }
        }
        return result
    }

    private func numberedInput(from segments: [MobileTranslationSegment]) -> String {
        segments.map { "\($0.id)=\($0.text)" }.joined(separator: "\n")
    }

    private func normalizedBearerSecret(_ secret: String) -> String {
        let trimmed = secret.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.lowercased().hasPrefix("bearer ")
            ? String(trimmed.dropFirst("bearer ".count)).trimmingCharacters(in: .whitespacesAndNewlines)
            : trimmed
    }

    private func endpointURL(baseURL: String, endpointPath: String) throws -> URL {
        var base = baseURL.trimmingCharacters(in: .whitespacesAndNewlines)
        while base.hasSuffix("/") { base.removeLast() }

        let path = endpointPath.hasPrefix("/") ? endpointPath : "/" + endpointPath
        let lowerBase = base.lowercased()
        let lowerPath = path.lowercased()
        let urlString: String
        if lowerBase.hasSuffix(lowerPath) {
            urlString = base
        } else if lowerBase.hasSuffix("/v1"), lowerPath.hasPrefix("/v1/") {
            urlString = base + String(path.dropFirst("/v1".count))
        } else {
            urlString = base + path
        }

        guard !base.isEmpty,
              let url = URL(string: urlString),
              let scheme = url.scheme?.lowercased(), scheme == "https",
              url.host != nil else {
            throw MobileTranslationProviderError.invalidConfiguration
        }
        return url
    }
}

public protocol SubtitleProcessor: Sendable {
    func process(
        _ request: MobileSubtitleProcessingRequest,
        progress: @escaping @Sendable (MobileTaskProgress) -> Void
    ) async throws -> MobileTaskArtifact
}

public protocol RenderExporter: Sendable {
    func export(
        _ request: MobileRenderRequest,
        progress: @escaping @Sendable (MobileTaskProgress) -> Void
    ) async throws -> MobileTaskResult
}

public protocol SecureCredentialStore: Sendable {
    func saveCredential(_ secret: String, for reference: SecureCredentialReference) async throws -> SecureCredentialReference
    func deleteCredential(_ reference: SecureCredentialReference) async throws
    func hasCredential(_ reference: SecureCredentialReference) async throws -> Bool
    func credential(for reference: SecureCredentialReference) async throws -> String?
}

public protocol TaskRepository: Sendable {
    func loadTasks() async throws -> [MobileTaskSnapshot]
    func saveTask(_ snapshot: MobileTaskSnapshot) async throws
    func removeTask(id: String) async throws
}
