@testable import MoongateMobileCore
import XCTest

final class LocalizerTests: XCTestCase {
    func testAllLanguageTablesHaveIdenticalKeySets() {
        let en = Set(LocalizationTables.en.keys)
        let hans = Set(LocalizationTables.zhHans.keys)
        let hant = Set(LocalizationTables.zhHant.keys)
        XCTAssertEqual(en, hans, "en 与 zh-Hans 键集不一致：\(en.symmetricDifference(hans))")
        XCTAssertEqual(en, hant, "en 与 zh-Hant 键集不一致：\(en.symmetricDifference(hant))")
        XCTAssertFalse(en.isEmpty)
    }

    func testNoTableValueIsEmpty() {
        for (lang, table) in [("en", LocalizationTables.en),
                              ("zh-Hans", LocalizationTables.zhHans),
                              ("zh-Hant", LocalizationTables.zhHant)] {
            for (key, value) in table {
                XCTAssertFalse(
                    value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
                    "\(lang) 的 \(key) 文案为空"
                )
            }
        }
    }

    func testMissingKeyFallsBackToKeyItself() {
        XCTAssertEqual(LocalizedStrings.string("L.Nonexistent.Key", language: .en), "L.Nonexistent.Key")
    }

    func testLookupReturnsLocalizedValue() {
        XCTAssertEqual(LocalizedStrings.string(L.Common.done, language: .en), "Done")
        XCTAssertEqual(LocalizedStrings.string(L.Common.done, language: .zhHans), "完成")
        XCTAssertEqual(LocalizedStrings.string(L.App.title, language: .zhHant), "月之門")
        XCTAssertEqual(LocalizedStrings.string(L.Main.enqueue, language: .zhHant), "加入佇列")
    }

    func testMainWindowPrimaryFlowStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Main.urlPlaceholderMultiline, language: .en), "Paste one or more video links")
        XCTAssertEqual(LocalizedStrings.string(L.Main.idleTitle, language: .zhHans), "粘贴链接，下载网页里的视频")
        XCTAssertEqual(LocalizedStrings.string(L.Main.idleTitle, language: .zhHant), "貼上連結，下載網頁裡的影片")
        XCTAssertEqual(LocalizedStrings.string(L.Main.loading, language: .en), "Parsing...")
        XCTAssertEqual(LocalizedStrings.format(L.Main.videoCount, language: .zhHant, [3]), "這個頁面裡有 3 部影片")
        XCTAssertEqual(LocalizedStrings.string(L.Main.backToList, language: .en), "Back to list")
        XCTAssertEqual(LocalizedStrings.format(L.Main.saveToVideoFolder, language: .en, ["Demo"]), "Save to Downloads/Demo and keep adding links")
    }

    func testReadyPageFormatAndSubtitleStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Ready.formatSection, language: .en), "Format")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.outputOptionsSection, language: .zhHans), "输出选项")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.outputOptionsSection, language: .zhHant), "輸出選項")
        XCTAssertEqual(LocalizedStrings.format(L.Ready.keepSourceFormatWithSource, language: .en, ["VP9 · webm"]), "Keep source format (VP9 · webm)")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.h264ReencodeWarning, language: .zhHant), "跨編碼轉 H.264 需重新編碼，較慢。")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.autoGenerated, language: .en), "Auto-generated")
        XCTAssertEqual(LocalizedStrings.format(L.Ready.autoGeneratedSubtitleLabel, language: .zhHant, ["英文"]), "英文，自動生成字幕")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.selected, language: .en), "Selected")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.notSelected, language: .zhHant), "未選擇")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.noSubtitleSelected, language: .en), "Select a subtitle above first")
        XCTAssertEqual(LocalizedStrings.string(L.Ready.sourceAlreadyTargetBurn, language: .zhHant), "這條字幕已是目標語言，將直接燒錄（不翻譯）")
        XCTAssertEqual(
            LocalizedStrings.format(L.Ready.willTranslateSubtitle, language: .en, ["English"]),
            "Will translate: English"
        )
        XCTAssertEqual(LocalizedStrings.string(L.Ready.appleTranslationOpenSettingsHelp, language: .zhHans), "只打开 App 设置查看系统侧步骤；不会直接打开系统设置、下载语言包、保存配置或切换引擎。")
    }

    func testQueueStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Queue.title, language: .en), "Download queue")
        XCTAssertEqual(LocalizedStrings.string(L.Queue.title, language: .zhHans), "下载队列")
        XCTAssertEqual(LocalizedStrings.string(L.Queue.title, language: .zhHant), "下載佇列")
        XCTAssertEqual(LocalizedStrings.format(L.Queue.taskCount, language: .en, [3]), "3 tasks")
        XCTAssertEqual(LocalizedStrings.format(L.Queue.taskCount, language: .zhHant, [3]), "3 個任務")
        XCTAssertEqual(LocalizedStrings.format(L.Queue.downloadingPercent, language: .en, [42]), "Downloading 42%")
        XCTAssertEqual(LocalizedStrings.format(L.Queue.failedWithReason, language: .zhHant, ["網路中斷"]), "失敗：網路中斷")
        XCTAssertEqual(LocalizedStrings.format(L.Queue.openQueueWithLabel, language: .en, ["2 in progress"]), "Open download queue: 2 in progress")
        XCTAssertEqual(LocalizedStrings.string(L.Queue.removeHint, language: .zhHant), "只從佇列移除這個任務，不會刪除已下載檔案")
    }

    func testSettingsPrimaryConfigurationStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Settings.languageSection, language: .en), "Language")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.languageSection, language: .zhHans), "语言")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.languageSection, language: .zhHant), "語言")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.followSystem, language: .en), "Follow system")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.langHans, language: .zhHant), "简体中文")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.langHant, language: .en), "繁體中文")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.aiSettingsSection, language: .en), "AI settings")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.smartTranslationPrompts, language: .zhHant), "智慧翻譯提示詞")
        XCTAssertEqual(LocalizedStrings.format(L.Settings.fetchedModels, language: .en, [3]), "Fetched 3 models")
        XCTAssertEqual(LocalizedStrings.format(L.Settings.connectionFailed, language: .zhHant, ["逾時"]), "連線失敗：逾時")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.advancedDetails, language: .en), "Advanced details")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.sourceLanguage, language: .zhHant), "來源語言")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.currentEngine, language: .en), "Current engine")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.appleActionOpenLanguageSettingsHelp, language: .zhHans), "打开系统设置，由你在系统里下载语言包；App 不会自动下载")
    }

    func testSettingsSecondarySectionsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Settings.performanceSection, language: .en), "Performance")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.styleSection, language: .zhHans), "字幕样式")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.subtitleStyle, language: .en), "Translated subtitle style")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.subtitleStyleBilingual, language: .zhHant), "雙語（原文 + 譯文）")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.subtitleStyleChineseOnly, language: .zhHans), "仅译文")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.burnSection, language: .zhHant), "燒錄與轉碼")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.followSourceHEVC, language: .en), "Follow source (keep HEVC sources as HEVC)")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.loginSection, language: .zhHant), "站點登入")
        XCTAssertEqual(LocalizedStrings.string(L.Settings.clearLoginAction, language: .en), "Clear login info")
        XCTAssertEqual(
            LocalizedStrings.format(L.Settings.loginSaved, language: .zhHant, ["6月17日"]),
            "已儲存登入資訊（6月17日匯出）"
        )
    }

    func testFailedStateStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Failed.technicalDetails, language: .en), "Technical details")
        XCTAssertEqual(LocalizedStrings.string(L.Failed.login, language: .zhHant), "前往登入")
        XCTAssertEqual(LocalizedStrings.string(L.Failed.restart, language: .zhHans), "重新开始")
    }

    func testAppAndSummaryStringsAreLocalized() {
        XCTAssertEqual(
            LocalizedStrings.format(L.App.abortRunningTasks, language: .en, [2]),
            "There are 2 active tasks in the queue. Closing will stop them all."
        )
        XCTAssertEqual(
            LocalizedStrings.format(L.App.abortPausedTasks, language: .zhHant, [3, 1]),
            "佇列中還有 3 個任務（含 1 個已暫停），關閉會全部中止。"
        )
        XCTAssertEqual(LocalizedStrings.string(L.App.keepTasks, language: .en), "Keep tasks and continue")
        XCTAssertEqual(LocalizedStrings.string(L.App.abortTasks, language: .zhHant), "中止任務並關閉")
        XCTAssertEqual(LocalizedStrings.string(L.Summary.title, language: .en), "Summarize video")
        XCTAssertEqual(LocalizedStrings.string(L.Summary.idleDescription, language: .zhHant), "下載前先用 AI 看一眼這是什麼影片。")
        XCTAssertEqual(LocalizedStrings.string(L.Summary.retry, language: .en), "Summarize again")
    }

    func testLoginStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.format(L.Login.title, language: .en, ["YouTube"]), "Log in to YouTube")
        XCTAssertEqual(LocalizedStrings.format(L.Login.title, language: .zhHant, ["YouTube"]), "登入 YouTube")
        XCTAssertEqual(LocalizedStrings.string(L.Login.saveLogin, language: .en), "Save login")
        XCTAssertEqual(LocalizedStrings.string(L.Login.saving, language: .zhHant), "儲存中…")
        XCTAssertEqual(LocalizedStrings.string(L.Login.cookieReady, language: .zhHans), "已检测到当前站点 Cookie")
        XCTAssertEqual(LocalizedStrings.string(L.Login.loadFailed, language: .zhHant), "頁面載入失敗，請檢查網路後重試")
    }

    func testDependencySetupStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Dependency.title, language: .en), "Install dependencies")
        XCTAssertEqual(LocalizedStrings.string(L.Dependency.title, language: .zhHans), "安装依赖组件")
        XCTAssertEqual(LocalizedStrings.string(L.Dependency.title, language: .zhHant), "安裝依賴元件")
        XCTAssertEqual(LocalizedStrings.string(L.Dependency.openBrew, language: .en), "Open brew.sh")
        XCTAssertEqual(LocalizedStrings.string(L.Dependency.statusInstalled, language: .zhHant), "已安裝")
        XCTAssertEqual(
            LocalizedStrings.format(L.Dependency.installIncomplete, language: .en, [7]),
            "Installation did not finish (exit code 7). Check the log."
        )
        XCTAssertEqual(
            LocalizedStrings.format(L.Dependency.componentAccessibilityLabel, language: .zhHant, ["ffmpeg", "字幕燒錄"]),
            "ffmpeg，字幕燒錄"
        )
    }

    func testUpdateStringsAreLocalized() {
        XCTAssertEqual(LocalizedStrings.string(L.Update.sectionTitle, language: .en), "Updates")
        XCTAssertEqual(LocalizedStrings.string(L.Update.sectionTitle, language: .zhHans), "更新")
        XCTAssertEqual(LocalizedStrings.string(L.Update.upToDate, language: .zhHant), "已是最新版本")
        XCTAssertEqual(
            LocalizedStrings.format(L.Update.available, language: .en, ["0.7.0"]),
            "New version v0.7.0 available"
        )
        XCTAssertEqual(
            LocalizedStrings.format(L.Update.downloadingPercent, language: .zhHant, [42]),
            "正在下載更新…42%"
        )
        XCTAssertEqual(
            LocalizedStrings.format(L.Update.installDirectoryNotWritable, language: .en, ["/Applications"]),
            "Moongate cannot write to /Applications, so automatic installation cannot continue. Run as an administrator or download manually from GitHub."
        )
    }

    func testAutoResolvesByPreferredLanguage() {
        XCTAssertEqual(AppLanguage.auto.resolved(preferredLanguages: ["en-US"]), .en)
        XCTAssertEqual(AppLanguage.auto.resolved(preferredLanguages: ["zh-Hans-CN"]), .zhHans)
        XCTAssertEqual(AppLanguage.auto.resolved(preferredLanguages: ["zh-Hant-TW"]), .zhHant)
        XCTAssertEqual(AppLanguage.auto.resolved(preferredLanguages: ["zh-TW"]), .zhHant)
        XCTAssertEqual(AppLanguage.auto.resolved(preferredLanguages: ["fr-FR"]), .en)
        // 显式选择优先于系统语言。
        XCTAssertEqual(AppLanguage.zhHant.resolved(preferredLanguages: ["en-US"]), .zhHant)
    }
}
