package com.moongate.mobile.domain

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MobileInputSource(
    val id: String,
    val kind: Kind,
    val value: String,
    val displayName: String? = null,
) {
    @Serializable
    enum class Kind {
        @SerialName("pastedURL")
        PASTED_URL,

        @SerialName("clipboardURL")
        CLIPBOARD_URL,

        @SerialName("sharedURL")
        SHARED_URL,

        @SerialName("importedFile")
        IMPORTED_FILE,
    }
}

@Serializable
enum class MobileCandidateKind {
    @SerialName("directFile")
    DIRECT_FILE,

    @SerialName("hlsStream")
    HLS_STREAM,

    @SerialName("webPageVideo")
    WEB_PAGE_VIDEO,

    @SerialName("importedFile")
    IMPORTED_FILE,
}

@Serializable
enum class MobileUnsupportedReason {
    @SerialName("requiresDesktopExtractor")
    REQUIRES_DESKTOP_EXTRACTOR,

    @SerialName("drmOrAccessControl")
    DRM_OR_ACCESS_CONTROL,

    @SerialName("loginRequired")
    LOGIN_REQUIRED,

    @SerialName("unsupportedFormat")
    UNSUPPORTED_FORMAT,

    @SerialName("unknown")
    UNKNOWN,
}

@Serializable
data class MobileVideoCandidate(
    val id: String,
    val sourceURL: String,
    val kind: MobileCandidateKind,
    val title: String,
    val detail: String? = null,
    val unsupportedReason: MobileUnsupportedReason? = null,
) {
    val isSupportedOnMobile: Boolean
        get() = unsupportedReason == null
}

@Serializable
data class MobileFormatChoice(
    val id: String,
    val label: String,
    val detail: String? = null,
    val height: Int? = null,
    val isAudioOnly: Boolean = false,
)

@Serializable
data class MobileSubtitleChoice(
    val id: String,
    val languageCode: String,
    val label: String,
    val isAutoGenerated: Boolean,
)

@Serializable
data class MobileVideoInfo(
    val candidate: MobileVideoCandidate,
    val videoID: String,
    val title: String,
    val durationSeconds: Double? = null,
    val thumbnailURL: String? = null,
    val formats: List<MobileFormatChoice> = emptyList(),
    val subtitles: List<MobileSubtitleChoice> = emptyList(),
) {
    val recommendedFormat: MobileFormatChoice?
        get() = formats.firstOrNull { !it.isAudioOnly } ?: formats.firstOrNull()

    val hasSubtitleOptions: Boolean
        get() = subtitles.isNotEmpty()
}

@Serializable
enum class MobileAddSessionState {
    @SerialName("idle")
    IDLE,

    @SerialName("analyzing")
    ANALYZING,

    @SerialName("candidateSelection")
    CANDIDATE_SELECTION,

    @SerialName("ready")
    READY,

    @SerialName("unsupported")
    UNSUPPORTED,

    @SerialName("failed")
    FAILED,
}

@Serializable
data class MobileAddSessionSnapshot(
    val id: String,
    val input: MobileInputSource? = null,
    val state: MobileAddSessionState = MobileAddSessionState.IDLE,
    val candidates: List<MobileVideoCandidate> = emptyList(),
    val selectedCandidateID: String? = null,
    val videoInfo: MobileVideoInfo? = null,
    val selectedFormatID: String? = null,
    val selectedSubtitleIDs: List<String> = emptyList(),
    val selectedAutoSubtitleIDs: List<String> = emptyList(),
    val error: MobileTaskError? = null,
) {
    val selectedCandidate: MobileVideoCandidate?
        get() = selectedCandidateID?.let { id -> candidates.firstOrNull { it.id == id } }

    fun downloadRequest(
        id: String,
        exportProfile: MobileExportProfile = MobileExportProfile(),
    ): MobileDownloadRequest? {
        val videoInfo = videoInfo ?: return null
        val candidate = selectedCandidate ?: videoInfo.candidate

        return MobileDownloadRequest(
            id = id,
            sourceURL = candidate.sourceURL,
            candidateID = candidate.id,
            videoID = videoInfo.videoID,
            formatID = selectedFormatID ?: videoInfo.recommendedFormat?.id ?: return null,
            subtitleIDs = selectedSubtitleIDs,
            autoSubtitleIDs = selectedAutoSubtitleIDs,
            exportProfile = exportProfile,
            preferredTitle = videoInfo.title,
        )
    }
}

@Serializable
data class MobileDownloadRequest(
    val id: String,
    val sourceURL: String,
    val candidateID: String,
    val videoID: String,
    val formatID: String,
    val subtitleIDs: List<String> = emptyList(),
    val autoSubtitleIDs: List<String> = emptyList(),
    val exportProfile: MobileExportProfile = MobileExportProfile(),
    val preferredTitle: String? = null,
)
